from datetime import date, datetime
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field, field_validator, model_validator


class MarketRegime(str, Enum):
    """Identified market regimes driving the trade thesis."""
    BULLISH_TRENDING = "BULLISH_TRENDING"
    BEARISH_TRENDING = "BEARISH_TRENDING"
    SIDEWAYS_CONSOLIDATION = "SIDEWAYS_CONSOLIDATION"
    HIGH_VOLATILITY = "HIGH_VOLATILITY"
    LOW_VOLATILITY = "LOW_VOLATILITY"


class InstrumentType(str, Enum):
    """Financial instrument classification."""
    EQUITY = "EQUITY"
    OPTION = "OPTION"


class OrderSide(str, Enum):
    """Basic order sides."""
    BUY = "BUY"
    SELL = "SELL"


class OptionType(str, Enum):
    """Option contract types."""
    CALL = "CALL"
    PUT = "PUT"


class OptionAction(str, Enum):
    """Option leg specific execution actions."""
    BUY_TO_OPEN = "BUY_TO_OPEN"
    SELL_TO_OPEN = "SELL_TO_OPEN"
    BUY_TO_CLOSE = "BUY_TO_CLOSE"
    SELL_TO_CLOSE = "SELL_TO_CLOSE"


class OptionLeg(BaseModel):
    """Detailed specification for an individual options contract leg."""
    strike_price: float = Field(..., gt=0, description="Strike price of the option leg.")
    expiration_date: str = Field(
        ...,
        description="Expiration date in YYYY-MM-DD format.",
        examples=["2026-09-18"]
    )
    option_type: OptionType = Field(..., description="Option type: CALL or PUT.")
    action: OptionAction = Field(..., description="Action for this leg (e.g., BUY_TO_OPEN, SELL_TO_OPEN).")
    quantity: int = Field(default=1, gt=0, description="Number of contracts for this specific leg.")

    @field_validator("expiration_date")
    @classmethod
    def validate_expiration_date(cls, value: str) -> str:
        try:
            parsed = date.fromisoformat(value)
            # Expiration should not be in the past
            if parsed < date.today():
                raise ValueError(f"Expiration date {value} cannot be in the past.")
        except Exception as e:
            raise ValueError(f"Invalid expiration_date format '{value}'. Expected YYYY-MM-DD. Error: {e}")
        return value


class TradeIntent(BaseModel):
    """
    Validated trade proposal generated by AI / Market Analysis Agent.
    Strictly adheres to project guardrails: LLM proposes structured JSON only.
    """
    symbol: str = Field(..., min_length=1, max_length=10, description="Underlying ticker symbol (e.g. SPY, AAPL, NVDA).")
    market_regime: MarketRegime = Field(..., description="Market regime detected during analysis.")
    instrument_type: InstrumentType = Field(..., description="Type of instrument to trade (EQUITY or OPTION).")
    strategy_name: Optional[str] = Field(
        default=None,
        description="Strategy name (e.g. LONG_CALL, BEAR_PUT_SPREAD, IRON_CONDOR, EQUITY_HEDGE)."
    )
    action: OrderSide = Field(default=OrderSide.BUY, description="Primary intent side: BUY or SELL.")
    quantity: int = Field(default=1, gt=0, description="Quantity of shares or standard contract units.")
    estimated_entry_price: Optional[float] = Field(
        default=None,
        gt=0,
        description="Estimated price per share/contract at entry."
    )
    target_price: float = Field(..., gt=0, description="Target profit exit price for the underlying or strategy.")
    stop_loss: float = Field(..., gt=0, description="Hard stop-loss exit price.")
    options_legs: List[OptionLeg] = Field(
        default_factory=list,
        description="List of option legs if instrument_type is OPTION."
    )
    reasoning: str = Field(
        ...,
        min_length=10,
        description="Comprehensive rationale explaining regime alignment, catalyst, and risk/reward setup."
    )
    confidence_score: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Model confidence score between 0.0 and 1.0."
    )
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Timestamp when the trade proposal was formed."
    )

    @field_validator("symbol")
    @classmethod
    def normalize_symbol(cls, value: str) -> str:
        cleaned = value.strip().upper()
        if not cleaned:
            raise ValueError("Symbol cannot be empty.")
        return cleaned

    @model_validator(mode="after")
    def validate_instrument_and_legs(self) -> "TradeIntent":
        # Options validation
        if self.instrument_type == InstrumentType.OPTION:
            if not self.options_legs or len(self.options_legs) == 0:
                raise ValueError("options_legs cannot be empty when instrument_type is OPTION.")
            
            # Check defined-risk rule for options: Naked short options without long protection are prohibited
            short_legs = [leg for leg in self.options_legs if leg.action == OptionAction.SELL_TO_OPEN]
            long_legs = [leg for leg in self.options_legs if leg.action == OptionAction.BUY_TO_OPEN]
            
            if short_legs and not long_legs:
                raise ValueError(
                    "Pure naked short options are prohibited by project risk rules. "
                    "Option strategies with short legs must include long hedging legs (defined risk spreads)."
                )
        elif self.instrument_type == InstrumentType.EQUITY:
            if self.options_legs and len(self.options_legs) > 0:
                raise ValueError("options_legs must be empty when instrument_type is EQUITY.")

        return self
